version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
    build:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - run : echo ${CIRCLE_BRANCH}
            # - run :
            #     name : "Stup custom environment variables"
            #     command: |
            #     echo 'export ACCESS_KEY = AKIA2Z45VZLJLW2VR56U' >> $BASH_ENV
            #     echo 'export SECRET_ACESS_KEY = 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' >> $BASH_ENV
            - restore_cache:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            - run: npm install --save
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
            - run: if [ "${CIRCLE_BRANCH}" == "staging" ]; then npm run build-qa elif [ "${CIRCLE_BRANCH}" == "master" ]; then npm run build-prod else npm run build-dev fi
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist

# The deploy job
deploy:
    working_directory: ~/project
    docker:
        - image: circleci/node:6.10-browsers
    steps:
        # Log the current branch
        - run:
            name: Show current branch
            command: echo ${CIRCLE_BRANCH}
        # Restore cache from the build job which contains the
        # dist folder that needs to be deployed
        - restore_cache:
            key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        # Install AWS cli
        - run:
            name: Install aws cli
            command:
                sudo apt-get -y -qq install awscli
        # Set the signature version for the S3 auth
        - run:
            name: Setting Signature Version 4 for S3 Request Authentication
            command: aws configure set aws_acess_key_id AKIA2Z45VZLJLW2VR56U | aws configure set aws_secret_acess_key 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 | aws configure set default.region sa-east-1
        # Deploy to the S3 bucket corresponding to the current branch
        - run:
            name: Deploy to S3
            command: |
                if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                    aws --region sa-east-1 s3 sync dist s3://angularbdb/ --delete
                elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                    aws --region sa-east-1 s3 sync dist s3://angularbdb/ --delete
                elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                    aws --region sa-east-1 s3 sync dist s3://angularbdb/ --delete
                fi


orbs:
    aws-s3: circleci/aws-s3@1.0.16