version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-s3: circleci/aws-s3@1.0.16
jobs:
    build:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - run : echo ${CIRCLE_BRANCH}
            - run: npm install --save
            - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
            - run: npm run build
            - run : sudo apt-get -y -qq install awscli
            - run : aws configure set aws_acess_key_id AKIA2Z45VZLJLW2VR56U | aws configure set aws_secret_acess_key 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 | aws configure set default.region sa-east-1
            - run : aws s3 sync dist/front s3://angularbdb